#ifndef __GPIO_wxgui__
#define __GPIO_wxgui__

/**
@file
Subclass of GPIO_view, which is generated by wxFormBuilder.
*/

#include "utilities_gui.h"

//// end generated include
class LMScomms;
/** Implementing GPIO_view */
class GPIO_wxgui : public GPIO_view
{
	protected:
		// Handlers for GPIO_view events.
		void OnUpdateClick ( wxCommandEvent& event );
		void OnChangeGPIODirection ( wxCommandEvent& event );
	public:
		/** Constructor */
		GPIO_wxgui( wxWindow* parent );
	//// end generated class members
        GPIO_wxgui(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString &title = wxEmptyString, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize, long styles = 0);
//        virtual void Initialize(LMScomms* pCtrPort, LMScomms* pDataPort);
        virtual void Initialize(LMScomms* pCtrPort);
    protected:
        LMScomms* ctrPort;
//        LMScomms* dataPort;
};

#endif // __GPIO_wxgui__
