#ifndef __lms8001_mainPanel__
#define __lms8001_mainPanel__

/**
@file
Subclass of mainPanel, which is generated by wxFormBuilder.
*/

#include "lms8001_wxgui.h"

//// end generated include
class LMS8001;
class MCU_BD;
class lms8001_pnlMCU_BD_view;

/** Implementing mainPanel */
class lms8001_mainPanel : public mainPanel
{
	protected:
		// Handlers for mainPanel events.
		void OnNewProject( wxCommandEvent& event );
		void OnOpenProject( wxCommandEvent& event );
		void OnSaveProject( wxCommandEvent& event );
		void OnUploadAll( wxCommandEvent& event );
		void OnDownloadAll( wxCommandEvent& event );
		void OnReset( wxCommandEvent& event );
		void OnRegistersTest( wxCommandEvent& event );
        void OnSwitchChannel(wxCommandEvent& event);
//mb added line
		void OnUploadPanel(wxCommandEvent& event);
//        void OnSwitchToChannelA(wxCommandEvent& event);
//        void OnSwitchToChannelB(wxCommandEvent& event);
		void Onnotebook_modulesPageChanged( wxNotebookEvent& event );
        void OnResetChip(wxCommandEvent& event);        
	public:
		/** Constructor */
		lms8001_mainPanel( wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize, long style = wxTAB_TRAVERSAL );        
	//// end generated class members
        void UpdateVisiblePanel();
        ~lms8001_mainPanel();
        void UpdateGUI();
        void Initialize(LMS8001* pControl);
protected:
        lms8001_pnlMCU_BD_view *mTabMCU;
        LMS8001* lmsControl;
        MCU_BD* mcuControl;
};

#endif // __lms8001_mainPanel__
