#ifndef __LMS8SuiteAppFrame__
#define __LMS8SuiteAppFrame__

/**
@file
Subclass of AppFrame_view, which is generated by wxFormBuilder.
*/

#include "lms8suiteApp_gui.h"

//// end generated include

class LMScomms;
class LMS8001;
class pnlMiniLog;
//class fftviewer_frFFTviewer;
class ADF4002;
class ADF4002_wxgui;
class Si5351C;
class Si5351C_wxgui;
//class LMS_Programing_wxgui;
//class RFSpark_wxgui;
//class HPM7_wxgui;
//class FPGAcontrols_wxgui;
//class Myriad7_wxgui;
class dlgDeviceInfo;
class SPI_wxgui;
class GPIO_wxgui;

//class LMS7002M_Novena_wxgui;

/** Implementing AppFrame */
class LMS8SuiteAppFrame : public AppFrame_view
{
	protected:
		// Handlers for AppFrame events.
		void OnClose( wxCloseEvent& event );
		void OnQuit( wxCommandEvent& event );
		void OnShowConnectionSettings( wxCommandEvent& event );
		void OnAbout( wxCommandEvent& event );
        void OnControlBoardConnect(wxCommandEvent& event);
//        void OnDataBoardConnect(wxCommandEvent& event);
        void HandleLMSevent(wxCommandEvent& event);
//        void OnFFTviewerClose(wxCloseEvent& event);
//        void OnShowFFTviewer(wxCommandEvent& event);
        void OnADF4002Close(wxCloseEvent& event);
        void OnShowADF4002(wxCommandEvent& event);
        void OnSi5351Close(wxCloseEvent& event);
        void OnShowSi5351C(wxCommandEvent& event);
//        void OnProgramingClose(wxCloseEvent& event);
//        void OnShowPrograming(wxCommandEvent& event);
//        void OnRFSparkClose(wxCloseEvent& event);
//        void OnShowRFSpark(wxCommandEvent& event);
//        void OnHPM7Close(wxCloseEvent& event);
//        void OnShowHPM7(wxCommandEvent& event);
//        void OnFPGAcontrolsClose(wxCloseEvent& event);
//        void OnShowFPGAcontrols(wxCommandEvent& event);
//        void OnMyriad7Close(wxCloseEvent& event);
//        void OnShowMyriad7(wxCommandEvent& event);
        void OnDeviceInfoClose(wxCloseEvent& event);
        void OnShowDeviceInfo(wxCommandEvent& event);
        void OnSPIClose(wxCloseEvent& event);
		void OnGPIOClose(wxCloseEvent& event);
        void OnShowSPI(wxCommandEvent& event);
		void OnShowGPIO(wxCommandEvent& event);
		void OnShowMeasurements(wxCommandEvent& event);
		void OnMeasurementsClose(wxCloseEvent& event);
//        void OnNovenaClose(wxCloseEvent& event);
//        void OnShowNovena(wxCommandEvent& event);
    public:
		/** Constructor */
		LMS8SuiteAppFrame( wxWindow* parent );
	//// end generated class members
		virtual ~LMS8SuiteAppFrame();
	protected:
        void OnLogDataTransfer(bool Tx, const unsigned char* data, const unsigned int length);
        void OnLogMessage(wxCommandEvent &event);
		static const wxString cWindowTitle;
		static const int cDeviceInfoCollumn = 1;
		static const int cDeviceVerRevMaskCollumn = 2;

        LMScomms* lms8controlPort;
//        LMScomms* streamBoardPort;
        LMS8001* lmsControl;
        pnlMiniLog* mMiniLog;
//        fftviewer_frFFTviewer* fftviewer;

        ADF4002* adfModule;
        ADF4002_wxgui* adfGUI;

        Si5351C* si5351module;
        Si5351C_wxgui* si5351gui;

//msavic
//        LMS_Programing_wxgui* programmer;
//        RFSpark_wxgui* rfspark;
//        HPM7_wxgui* hpm7;
//        FPGAcontrols_wxgui* fpgaControls;
//        Myriad7_wxgui* myriad7;
        dlgDeviceInfo* deviceInfo;
        SPI_wxgui* spi;
		GPIO_wxgui* gpio;
//        LMS7002M_Novena_wxgui* novenaGui;
};


#endif // __LMS8SuiteAppFrame__

